shared:
  image: node:8
jobs:
  pr:
    requires:
    - ~pr
    steps:
    - install: npm i -g screwdriver-command-validator
    - validate: command-validate -f ./sd-command.yaml
    - weird: |
        PKG="fenrirunbound/sd-cmd-validator/0.1.0/20180329221421"
        /opt/sd/bin/hab pkg install $PKG -c stable > /dev/null
        /opt/sd/bin/hab pkg exec $PKG sd-cmd-validator
  main:
    requires:
    - ~commit
    steps:
    - publish: sd-cmd publish -f ./sd-command.yaml

  test_in_prod:
    requires: main
    steps:
    - try_it: sd-cmd exec FenrirUnbound/mplater@0.1 "-i input.tmpl -o output.txt -x inputArg=this_is_it"
    - validate: diff comparison.txt output.txt
